#!/bin/sh
export SITE="New York, NY"
export DATE="5/3/2020"
export VE1="W2RTC"
export VE2="N2YGN"
export VE3="KD2HLE"
export CALL="N0CLU"
export FIRST="John"
export MIDDLE="Q"
export LAST="Doe"
export SUFFIX="Jr"
export ADDR="123 Main St"
export CITY="Brooklyn"
export STATE="NY"
export ZIP="12345"
export EARNED="E" # T|G|E for Tech, General, Extra
export PASS2=""
export PASS3=""
export PASS4="X"
export CRED3="X"
export CRED4=""
./CSCE.sh
